#!/bin/bash

# Admin Flow Manual Testing Checklist
# This script provides a structured checklist for manually testing the admin flow

echo "🔍 Admin Flow Manual Testing Checklist"
echo "======================================"
echo ""
echo "Prerequisites:"
echo "✅ Backend server is running on http://localhost:8080"
echo "✅ Frontend server is running on http://localhost:3000"
echo "✅ Admin user credentials are available"
echo ""
echo "Test Scenarios:"
echo ""

echo "📋 1. AUTHENTICATION & AUTHORIZATION"
echo "   [ ] Navigate to http://localhost:3000/login"
echo "   [ ] Login with admin credentials"
echo "   [ ] Verify redirect to /admin/dashboard"
echo "   [ ] Check JWT token is stored in localStorage"
echo "   [ ] Verify 'Admin Panel' sidebar is visible"
echo ""

echo "📊 2. DASHBOARD"
echo "   [ ] Navigate to /admin or /admin/dashboard"
echo "   [ ] Verify all metrics cards are displayed:"
echo "       - Total Students"
echo "       - Total Teachers"  
echo "       - Active Students"
echo "       - Active Teachers"
echo "       - Content statistics"
echo "   [ ] Check for loading states"
echo "   [ ] Check for error handling if API fails"
echo ""

echo "👥 3. STUDENTS MANAGEMENT"
echo "   [ ] Click 'Students' in sidebar"
echo "   [ ] Verify students list loads with pagination"
echo "   [ ] Test search functionality (type and wait 500ms)"
echo "   [ ] Test filters:"
echo "       - Status filter (all/enabled/disabled)"
echo "       - Board filter"
echo "       - Class level filter"
echo "   [ ] Test sorting (click column headers)"
echo "   [ ] Test pagination (next/previous)"
echo "   [ ] View student details (Eye icon)"
echo "   [ ] Edit student (Edit icon)"
echo "   [ ] Toggle student status (toggle switch)"
echo "   [ ] Verify refresh button works"
echo ""

echo "👨‍🏫 4. TEACHERS MANAGEMENT"
echo "   [ ] Click 'Teachers' in sidebar"
echo "   [ ] Verify teachers list loads"
echo "   [ ] Test search functionality"
echo "   [ ] Test status filter (pending/active/inactive/suspended)"
echo "   [ ] View teacher details"
echo "   [ ] Edit teacher information"
echo "   [ ] Toggle teacher status"
echo "   [ ] Verify teacher verification status"
echo ""

echo "📚 5. CONTENT MANAGEMENT"
echo "   [ ] Click 'Content Structure' in sidebar"
echo "   [ ] Test all 6 tabs:"
echo "       - Boards tab"
echo "       - Grades tab"
echo "       - Subjects tab"
echo "       - Chapters tab"
echo "       - Topics tab"
echo "       - Topic Notes tab"
echo "   [ ] Test Create operation (+ button)"
echo "   [ ] Test Edit operation (Edit icon)"
echo "   [ ] Test Delete operation (Trash icon)"
echo "   [ ] Test Active/Inactive toggle"
echo "   [ ] Test dropdown cascading (Grade depends on Board, etc.)"
echo ""

echo "📥 6. CONTENT IMPORT"
echo "   [ ] Click 'Content Import' in sidebar"
echo "   [ ] Test CSV file upload"
echo "   [ ] Verify validation errors are shown"
echo "   [ ] Test successful import"
echo "   [ ] Check progress indicator"
echo ""

echo "📈 7. ANALYTICS"
echo "   [ ] Click 'Analytics' in sidebar"
echo "   [ ] Verify charts and statistics display"
echo "   [ ] Test date range filters if available"
echo ""

echo "💰 8. PRICING RULES"
echo "   [ ] Click 'Pricing' in sidebar"
echo "   [ ] View pricing rules list"
echo "   [ ] Create new pricing rule"
echo "   [ ] Edit existing rule"
echo "   [ ] Toggle rule active status"
echo "   [ ] Delete pricing rule"
echo ""

echo "🔔 9. NOTIFICATIONS"
echo "   [ ] Click 'Notifications' in sidebar"
echo "   [ ] Send a test notification"
echo "   [ ] Schedule a notification"
echo "   [ ] View notification history"
echo ""

echo "💵 10. FEE WAIVERS"
echo "   [ ] Click 'Fee Waivers' in sidebar"
echo "   [ ] View waiver requests"
echo "   [ ] Approve a waiver request"
echo "   [ ] Reject a waiver request"
echo "   [ ] View waiver documentation"
echo ""

echo "🎨 11. UI/UX FEATURES"
echo "   [ ] Test dark mode toggle (Sun/Moon icon)"
echo "   [ ] Test responsive design:"
echo "       - Desktop (> 1024px)"
echo "       - Tablet (768px - 1024px)"
echo "       - Mobile (< 768px)"
echo "   [ ] Test sidebar collapse on mobile"
echo "   [ ] Verify all toast notifications work"
echo "   [ ] Check loading states and skeletons"
echo "   [ ] Test empty states (no data scenarios)"
echo ""

echo "🔒 12. SECURITY FEATURES"
echo "   [ ] Verify protected routes redirect if not authenticated"
echo "   [ ] Test token refresh (wait > 15 minutes)"
echo "   [ ] Test session expiration warning"
echo "   [ ] Test CSRF protection on mutations"
echo "   [ ] Verify XSS prevention (try entering <script> tags)"
echo ""

echo "🚪 13. LOGOUT"
echo "   [ ] Click 'Logout' button in header"
echo "   [ ] Verify redirect to home page"
echo "   [ ] Verify tokens are cleared from localStorage"
echo "   [ ] Verify cannot access admin pages after logout"
echo "   [ ] Try navigating back - should redirect to login"
echo ""

echo "⚠️ 14. ERROR HANDLING"
echo "   [ ] Test with backend offline"
echo "   [ ] Test with slow network (throttle in DevTools)"
echo "   [ ] Test with invalid API responses"
echo "   [ ] Verify user-friendly error messages"
echo "   [ ] Check console for errors (should be none)"
echo ""

echo "🎯 15. ACCESSIBILITY"
echo "   [ ] Test keyboard navigation (Tab key)"
echo "   [ ] Verify focus indicators are visible"
echo "   [ ] Test with screen reader (if available)"
echo "   [ ] Check color contrast in DevTools"
echo "   [ ] Verify ARIA labels are present"
echo ""

echo ""
echo "✅ Testing Complete!"
echo ""
echo "Report any issues found to the development team."
echo "Document issues with:"
echo "  - Screenshot"
echo "  - Steps to reproduce"
echo "  - Expected vs. actual behavior"
echo "  - Browser and OS version"
echo ""
