package com.ankurshala.backend.entity;

public enum NotificationType {
    BOOKING_REQUESTED,
    BOOKING_ACCEPTED,
    BOOKING_DECLINED,
    BOOKING_RESCHEDULED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_REMINDER_30M,
    BOOKING_REMINDER_5M,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    WALLET_CREDIT,
    WALLET_DEBIT,
    FEE_WAIVER_APPROVED,
    FEE_WAIVER_DECLINED,
    SYSTEM_ANNOUNCEMENT,
    GENERAL_ANNOUNCEMENT
}
